### ISSUE TITLE
Up For Grabs

### ISSUE THREAD

**Issue by bookercodes** [EvanHahn/lildash#207]
There is a bunch of low-hanging fruit here.

It could be worth tweaking [**your little script**](https://github.com/EvanHahn/add-a-bunch-of-GitHub-issues) to tag issues as being _"up-for-grabs"_ and to post lildash to [**up-for-grabs.net**](http://up-for-grabs.net).

Whaddaya think?

**Comment by EvanHahn** [comment]
This is a good idea but I don't want to do this until after the project gains some traction (if it ever does). I don't want to waste anyone's time!
